name: Commit Profile

on:
  push:
    branches:
      - main

  schedule:
    # Runs the job every hour
    - cron: "0 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{ github.ref }}"

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Decide to Run
        id: run_decision
        run: |
          # Generate a random number between 0 and 1
          decision=$(shuf -i 0-1 -n 1)
          echo "::set-output name=decision::$decision"

      - name: Stop if Not Running
        if: steps.run_decision.outputs.decision == '0'
        run: echo "Skipping this run"

      - name: Generate random commit count
        id: commit_count
        run: echo "::set-output name=count::$(($RANDOM % 13 + 3))"

      - name: Generate random commit messages
        id: commit_message
        run: |
          messages=("ðŸš€ Update README" "ðŸ”¥ Improve profile" "âœ¨ Enhance profile" "ðŸŽ¨ Style tweak" 
                    "ðŸ”§ Minor fix" "ðŸ”¨ Refactor README" "ðŸ’¡ Update content" "ðŸ’Ž" 
                    "ðŸ“ Revise README" "ðŸ” Optimize content" "ðŸŒŸ Enhance README" "ðŸ”„ Update profile" "ðŸš€ Improve layout")
          echo "::set-output name=message::${messages[$RANDOM % ${#messages[@]}]}"

      - name: Modify last update
        run: |
          d=$(date '+%Y-%m-%dT%H:%M:%SZ')
          echo $d > LAST_UPDATED

      - name: Commit changes
        if: steps.run_decision.outputs.decision == '1'
        run: |
          git config --local user.email "andiahmadyusup@gmail.com"
          git config --local user.name "andiahmadysx"
          git add -A

          count=${{ steps.commit_count.outputs.count }}
          for i in $(seq 1 $count); do
            message=${{ steps.commit_message.outputs.message }}
            git commit -m "$message"
          done

      - name: GitHub Push
        if: steps.run_decision.outputs.decision == '1'
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
