name: Commit Profile

on:
  push:
    branches:
      - main

  schedule:
    # Runs the job every hour
    - cron: "0 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{ github.ref }}"

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Decide to Run
        id: run_decision
        run: |
          # Generate a random number between 0 and 1
          decision=$(shuf -i 0-1 -n 1)
          echo "decision=$decision" >> $GITHUB_ENV

      - name: Stop if Not Running
        if: env.decision == '0'
        run: echo "Skipping this run"

      - name: Generate random commit count
        id: commit_count
        run: |
          count=$(($RANDOM % 13 + 3))
          echo "count=$count" >> $GITHUB_ENV

      - name: Generate random commit messages
        id: commit_message
        run: |
          messages=("ðŸš€ Update README" "ðŸ”¥ Improve profile" "âœ¨ Enhance page" "ðŸŽ¨ Style tweak" 
                    "ðŸ”§ Minor fix" "ðŸ”¨ Refactor README" "ðŸ’¡ Update content" "ðŸ’Ž Polish details" 
                    "ðŸ“ Revise README" "ðŸ” Optimize content" "ðŸŒŸ Enhance presentation" "ðŸ”„ Update profile" "ðŸš€ Improve layout")
          message=${messages[$RANDOM % ${#messages[@]}]}
          echo "message=$message" >> $GITHUB_ENV

      - name: Commit changes
        if: env.decision == '1'
        run: |
          git config --local user.email "andiahmadyusup@gmail.com"
          git config --local user.name "andiahmadysx"
          
          for i in $(seq 1 $count); do
            # Modify LAST_UPDATED to ensure each commit has a unique change
            echo "$i - $(date '+%Y-%m-%dT%H:%M:%SZ')" > LAST_UPDATED
            git add LAST_UPDATED
            git commit -m "$message"
          done

      - name: GitHub Push
        if: env.decision == '1'
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
